### ISSUE TITLE
Repository Organizer

### ISSUE THREAD

**Issue by suvanbalu** [abhishekdoifode1/Hacktoberfest2021#417]
Can I create a program for adding every programing files in a separate folder named after its programming language and organize it to contribute for hacktoberfest 2021 ?

**Comment by adi323** [comment]
yes

**Comment by adi323** [comment]
> Can I create a program for adding every programing files in a separate folder named after its programming language and organize it to contribute for hacktoberfest 2021 ?

yes

**Comment by thevirus69** [comment]
I have created an Chrome extension for random pictures and jokes using an Fetch API ( HTML , CSS , JS )
can i contribute with project for hacktoberfest 2021 ??
